### ISSUE TITLE
[Regression] Compilation error using gcc 4.9

### ISSUE THREAD

**Issue by olifre** [GenFit/GenFit#12]
Since the recent commit:
https://github.com/GenFit/GenFit/commit/4d7fe0f1572b1797c26f94268369685a11edd788
genfit2 does not compile for me on a gcc 4.9 based system anymore:

```
/var/tmp/portage/sci-physics/genfit-9999/work/genfit-9999/test/unitTests/main.cc:74:12: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
 using std::isnan;
            ^
In file included from /usr/include/features.h:365:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/x86_64-pc-linux-gnu/bits/os_defines.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/x86_64-pc-linux-gnu/bits/c++config.h:430,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/iostream:38,
                 from /var/tmp/portage/sci-physics/genfit-9999/work/genfit-9999/test/unitTests/main.cc:1:
/usr/include/bits/mathcalls.h:234:1: note: previous declaration ‘int isnan(double)’
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
```

Importing `isnan` from `std` into the global namespace of course makes it collide with the existing definition indirectly included via `iostream` (at least in the headers shipped with gcc 4.9.3). 

I suggest as a fix to drop the `using std::isnan` again, and just change the single use of `isnan` in `unitTests/main.cc` to explicitly use `std::isnan`.

**Comment by daritter** [comment]
If "std::isnan" works reliably also in C++98 than I'm all for it. Officially isnan has not been part of the Standard before C++11, that's the reason I proposed this ifdef in the first place.

PS: I don't think it's really the gcc version it's the libc version which depends on what works here but that's a minor detail.

**Comment by olifre** [comment]
Since by now genfit in any case uses C++11 features (see my https://github.com/GenFit/GenFit/pull/35 ), I guess this can be closed for good?
