### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by MarkusPrim** [GenFit/GenFit#18]
There is maybe some dead code in the project which could be removed. I will try to make a coverage report when using GenFit with basf2 to locate these blocks.

**Comment by nils-braun** [comment]
Are there already some news on this? If not, I  am willing to help :-)

**Comment by MarkusPrim** [comment]
Yep, see: https://github.com/GenFit/GenFit/tree/GenFit-18-RemoveDeadCode 
But still work in progress.
