### ISSUE TITLE
Broken default installation directories

### ISSUE THREAD

**Issue by olifre** [GenFit/GenFit#65]
Currently, `lib` and `include` are hardcoded.
This breaks on multilib-systems, which usually have `lib32` and `lib64`. 
For that reason, common practice in CMake is to use something like:
```
include(GNUInstallDirs)
INSTALL(TARGETS someBinary
	RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
	LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
```
etc.

**Comment by nils-braun** [comment]
Seems like a good idea! Do you want to create a pull request for this?
So all the tribute goes to you :-)
