### ISSUE TITLE
Finding Eigen3 breaks on a standard installation

### ISSUE THREAD

**Issue by olifre** [GenFit/GenFit#67]
I get:
```
CMake Error at CMakeLists.txt:39 (FIND_PACKAGE):
  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
```
However, I have:
```
/usr/share
/usr/share/cmake
/usr/share/cmake/Modules
/usr/share/cmake/Modules/FindEigen3.cmake
/usr/share/pkgconfig
/usr/share/pkgconfig/eigen3.pc
```
installed just fine. 
Modifying `CMakeLists.txt` from:
```
FIND_PACKAGE(Eigen3 REQUIRED NO_MODULE)
```
to
```
FIND_PACKAGE(Eigen3 REQUIRED)
```
fixes that:
```
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
```
I wonder why `NO_MODULE` is specified explicitly here, since it breaks any standard installation. 
Also, in case there is no module, a fallback to "config mode" will be done in any case. 

Is there a reason for it (then all distros out there need to patch GenFit), or can it be dropped for good?

**Comment by MarkusPrim** [comment]
I just tried to reproduce the error. I set up a new virtual machine and installed from scratch. I could not reproduce the error, the installation worked. 

I used ubuntu 16.04 with precompiled ROOT and the packaged libeigen3-dev.

**Comment by olifre** [comment]
> I used ubuntu 16.04 with precompiled ROOT and the packaged libeigen3-dev.

You appear to be correct, Ubuntu 16.04 and other Debian based distros do a strange packaging. 
As can be seen here:
https://packages.ubuntu.com/xenial/all/libeigen3-dev/filelist
they do indeed package `/usr/lib/cmake/eigen3/Eigen3Config.cmake`, which explains why things work for you. 

However, it breaks on RHEL, CentOS, Gentoo and probably many others. 

So let me repeat: Is there any sensible reason to specify `NO_MODULE`, or is this only added explicitly to break cmake so it only works on Debian-based OS?.

**Comment by MarkusPrim** [comment]
That was fast! No, there is no reason. I was just wondering. I will introduce the change. :+1:

**Comment by olifre** [comment]
Thanks! :smile:
For future reference, this is CentOS 7:
```
# rpm -ql eigen3-devel.noarch | grep cmake
/usr/share/cmake/Modules/FindEigen3.cmake
```
This is Gentoo:
```
$ equery f eigen | grep cmake
/usr/share/cmake
/usr/share/cmake/Modules
/usr/share/cmake/Modules/FindEigen3.cmake
```
And Ubuntu / Debian have:
```
/usr/lib/cmake/eigen3/Eigen3Config.cmake
/usr/lib/cmake/eigen3/UseEigen3.cmake
```
