### ISSUE TITLE
Install prefix needs fixed

### ISSUE THREAD

**Issue by whit2333** [GenFit/GenFit#90]
I wasted a day trying to figure out why it wasn't installing into `/usr/local` when building a container image even when explicitly set.

Please remove the lines in cmake/settings.cmake that prevent this! 

This is breaking a convention that has been around for 2 or more decades.

**Comment by whit2333** [comment]
OK, here is the PR
https://github.com/GenFit/GenFit/pull/91

I was a little hot in my initial comment. Please allow me to thank you for the awesome library!

Cheers

**Comment by nils-braun** [comment]
No no, I can absolutely understand your comment :-) And as you have fixed it immediately I can also not say anything against it :+1: 
Thanks!
