### ISSUE TITLE
Release number

### ISSUE THREAD

**Issue by ihepzhangyao** [GenFit/GenFit#99]
Would it possible to add the release number for GenFit?

**Comment by olifre** [comment]
I think this is essentially the same request as #42.

**Comment by ihepzhangyao** [comment]
Dear @olifre thank you for your reply. The first release of  the [CEPCSW](https://github.com/cepc/cepcsw)  is coming soon. But Genfit can NOT put into the official external libraries in the  due to the missing of the release number. Could the administrators @nils-braun @eckerpatrick consider this issue ASAP? Thank you very much!

**Comment by eckerpatrick** [comment]
@ihepzhangyao you're totally right, having a release number for GenFit would be really useful.
Sadly I don't have the capacity to take care of this at the moment. Maybe you could implement something yourself and I can check this in the end. Or maybe @olifre can help out with this.

As a temporary solution, you could keep a clone of the GenFit code in your repository and put it in the externals later on.

**Comment by olifre** [comment]
@eckerpatrick , I see you released a version on GitHub just now, many thanks!
Considering the version number, I think there is still an issue we should clarify. Checking on:
https://repology.org/project/genfit/versions
all distributions packaging GenFit interpreted "GenFit 2" as version `02.00.00`. So starting with `01.00.00` in this repository will be a problem for these distributions.

**Comment by eckerpatrick** [comment]
@olifre thanks for pointing this out. I was not aware of this. I will change it to 02-00-00.

**Comment by olifre** [comment]
> @olifre thanks for pointing this out. I was not aware of this. I will change it to 02-00-00.

Many thanks! 
This will allow distributions to adopt the scheme more seamlessly. 

Of course there's also the need to expose that version in the code at some point (to allow other code using `GenFit` to adapt to API changes, e.g. with C macros), but that is a second step then ;-).

**Comment by mirguest** [comment]
Many thanks!

Tao

**Comment by olifre** [comment]
> @olifre thanks for pointing this out. I was not aware of this. I will change it to 02-00-00.

@eckerpatrick Actually, the "safest" choice would be something slightly larger than `02-00-00`. The usual version comparison logic used by most projects is e.g. summarized here:
https://devmanual.gentoo.org/ebuild-writing/file-format/index.html#file-naming-rules
So currently:
Gentoo: `02.00.00_p20201231 > 02.00.00`
openSUSE: `2.0.0.1883 > 02.00.00`
(my guess is the latter is inspired by an SVN revision). `02.00.01` would be "large enough". 

However, for Gentoo I can also adapt to the new versioning, since I am the contributor of that `ebuild`, so this is not a pressing issue I think and I'll go with whatever you settle on (also `02-00-00`)  ;-).

**Comment by DraTeots** [comment]
From EIC here. We really appreciate you doing versions. In our software Gentfit is the only package we struggle with having no tags. And yes, please, don't forget to have repository tags.

**Comment by StefanBruens** [comment]
Would it be possible to tag a new minor release with all the bugfixes from GIT?

This would also implicitly fix any problems with versioning @olifre mentioned, i.e. version apparently going backwards.
